
import sys
import os
from dotenv import load_dotenv

# Add current directory to path
sys.path.append(os.getcwd())

load_dotenv()

from features.f1_debate_agent import debate_agent

print("Starting debate simulation for Article 356...")
try:
    result = debate_agent.simulate_debate(356)
    print("Debate Simulation Result:")
    print(f"Vulnerability Score: {result['vulnerability_score']}")
    print(f"Gov Argument: {result['government_argument'][:50]}...")
    print(f"Court Argument: {result['court_argument'][:50]}...")
    
    # Check if arguments match fallback (heuristic check)
    fallback_start = "Administrator can represent the state"
    if result['government_argument'].startswith(fallback_start):
        print("WARNING: Result matches fallback argument!")
    else:
        print("SUCCESS: Result appears to be generated by LLM.")
        
except Exception as e:
    print(f"Error during simulation: {e}")
    import traceback
    traceback.print_exc()
